### ISSUE TITLE
Ne pas envoyer de mail de renouvellement de jeton blacklisté

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/dashboard_api_entreprise#145]
Les clients ayant des jetons blacklistés peuvent recevoir des mails avertissant de l'expiration des-dits jetons.

Cela est source de confusion et il faudrait donc ne pas envoyer ces mails le cas échéant.

**Comment by skelz0r** [comment]
Ce n'est pas le bon dépot, je migre
