### ISSUE TITLE
Boutons de la page incidents 

### ISSUE THREAD

**Issue by brindu** [etalab/dashboard_api_entreprise#19]
Mettre à jour la position des boutons en s'inspirant de l'existant de la page de profil utilisateur pour le style.

**Comment by thimy** [comment]
Est-ce que tu peux préciser ce que tu as en tête ?

**Comment by brindu** [comment]
Je parlais d'uniformiser le style et le placement des différents boutons dans toute l'appli. Par exemple dans le dashboard les boutons sont sur la même ligne que le titre, sur la page incident il y a un saut de ligne.

<img width="450" alt="Capture d’écran 2019-11-26 à 13 41 48" src="https://user-images.githubusercontent.com/4283958/69634574-d1b6c400-1052-11ea-855d-285b4c901969.png">
<img width="721" alt="Capture d’écran 2019-11-26 à 13 42 07" src="https://user-images.githubusercontent.com/4283958/69634575-d1b6c400-1052-11ea-811b-0dcc08d76765.png">

Plus d'un an après l'ouverture de cette issue je pense que la passe de cohérence graphique est plus large que juste sur la page incident ^^ mais au départ c'était de ça que je voulais parler.
