### ISSUE TITLE
[BACKOFFICE] Tri du tableau liste des utilisateurs par colonne

### ISSUE THREAD

**Issue by giglemad** [etalab/dashboard_api_entreprise#40]
Ex de solution réalisant cela http://www.nicolas-verhoye.com/mettez-de-la-vie-dans-vos-tableaux-avec-jquery-datatables.html

L'idée est de faire quelque chose de simple sans forcément recourir à jquery, mais qui permette de naviguer dans la liste grandissante des utilisateurs plus aisément

**Comment by Haelle** [comment]
ajout de recherche par token ID et user ID
