### ISSUE TITLE
[BACKOFFICE] Afficher les taux de réponse HTTP par endpoint

### ISSUE THREAD

**Issue by hugolepetit** [etalab/dashboard_api_entreprise#42]
Aujourd'hui les taux globaux ne donnent que peu de renseignements, ni les clients, ni les administrateurs ne peuvent identifier assez finement les soucis en consultant l'interface

**Comment by Haelle** [comment]
virer la section taux de réponse
ajouter des colonnes pour le nombre d'appels (200s, 400s, 500s)
