### ISSUE TITLE
Ajouter un label sur l'ID du token

### ISSUE THREAD

**Issue by Haelle** [etalab/dashboard_api_entreprise#83]
Suite à une remarque lors de l'openlab il pourrait être judicieux d'ajouter un label devant l'UUID du token (cf image)
Voir ajouter une tooltip indiquant que c'est ça qu'il faut nous transmettre dans un mail de support.

![Screenshot_2019-10-18 Dashboard API Entreprise](https://user-images.githubusercontent.com/5159985/67080478-9f818f00-f195-11e9-911d-4b004b891d89.png)

**Comment by brindu** [comment]
Les deux AMHA, et là c'est sur la page des statistiques on peut aussi faire ça dans la liste des jetons de l'utilisateur.
