### ISSUE TITLE
Suppression ou fix de la liste complète des droits d'un utilisateur

### ISSUE THREAD

**Issue by brindu** [etalab/dashboard_api_entreprise#85]
Je veux parler de ceci, dans l'onglet "Profil" d'un utilisateur : 

<img width="1173" alt="Capture d’écran 2019-10-22 à 17 24 46" src="https://user-images.githubusercontent.com/4283958/67408405-36e14a80-f5b9-11e9-9224-9eaac20ec6d5.png">

Au départ, ceci avait été ajouté pour les utilisateurs dont on déléguait la création de jetons : ils pouvaient voir le périmètre qui leur avait été accordé. Du coup j'avais "élargi" la fonctionnalité pour les utilisateurs "normaux" en proposant une liste de droits ici qui soit l'agrégation de tous les droits d'accès sur l'ensemble de tous leurs jetons.

Aujourd'hui ça ne marche plus, et avant de réaliser le fix je me pose sérieusement la question de l'utilité de cette fonctionnalité. Vous en pensez quoi, y a-t-il toujours de la plus value à cette liste pour vous ? @Samuelfaure @hugolepetit @Haelle @mazalaigue

**Comment by Haelle** [comment]
Je pense que cette vue est devenue inutile

**Comment by brindu** [comment]
Pire que ça, j'ai eu plusieurs tickets d'utilisateurs qui nous remontent que leur jeton ne marche pas (sans le tester évidemment...) justement parce que cette vue est buggée 😞

**Comment by thimy** [comment]
La vue est cassée parce que `user` ne renvoie plus d'`allowed_roles`, j'ai rajouté une condition pour qu'on renvoie `false` s'il n'y a pas de rôles et fait en sorte qu'on n'affiche pas la vue suivant la condition, mais du coup si pour vous on peut supprimer la vue, je fais ça dans la foulée.
