### ISSUE TITLE
Ajouter un bouton "Archiver" un jeton

### ISSUE THREAD

**Issue by brindu** [etalab/dashboard_api_entreprise#96]
Dans la vue administrateur il existe déjà un bouton "Blacklister" pour les jetons, il faut aussi un deuxième bouton "Archiver", toujours avec une alerte pour valider l'action. 
L'action d'archivage est moins lourde de conséquences en terme d'action, pour la couleur.

**Comment by thimy** [comment]
J'ai pas trouvé de doc, c'est quel endpoint pour achiver un token ?

**Comment by brindu** [comment]
Il n'y a pas de doc pour ces APIs encore ^^ Même si il y en avait l'endpoint n'est pas encore mis en place (je termine dans la journée si tout se passe bien), c'est pour ça que j'avais juste parler d'un bouton ;)

**Comment by thimy** [comment]
Aaaah ok, j'étais prête à le faire marcher ! Je push ça soon. :)
